name: cobra
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - pip
  - streamlit==1.46.1
  - cobra==0.29.1
  - numpy==1.26.4
  - numpydoc==1.8.0
  - pandas==2.2.3
  - plotly==6.2.0
  - openpyxl
  - glpk 
  - pip:
    - python-libsbml

